export const FINANCIAL_TOOLS = [
  "Daily Cash Register",
  "Monthly Budget Tracker",
  "Job candidates tracker",
  "Land Records",
  "Membership list",
  "Milestone infographic timeline",
  "Office Inventory",
  "Passwords",
  "Vertical Timeline",
  "Annual Business Budget",
  "Bill Paying Checklist",
  "Business Expenses Budget",
  "Business Monthly Budget",
  "Cheque Register",
  "Expense Report",
  "Income & Expenses",
  "Investment Profile",
  "Investment Valuation",
  "Loan Amortization Schedule",
  "Retirement Financial Planner",
  "Small Business Petty Cash Log",
  "Customer Relationship Management"
];
